workflows:
  version: 2
  test-release:
    jobs:
      - test
      - test-mysql
      - test-postgres
      - test-redis
      - release:
          requires:
            - test
            - test-postgres
            - test-redis
          filters:
            branches:
              only: master

version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go test -v
      - run: go test -v ./cmd/...
      - run: go test -v ./config/...
      - run: go test -v ./execution/...
      - run: go test -v ./logical/...
      - run: go test -v ./parser/...
      - run: go test -v ./physical/...
      - run: go test -v ./storage/json/...

  test-mysql:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: mydb

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go test -v ./storage/mysql/...

  test-postgres:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: toor
          POSTGRES_DB: mydb

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go test -v ./storage/postgres/...

  test-redis:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
      - image: circleci/redis:latest

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go test -v ./storage/redis/...

  release:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go install -v ./...

      - store_artifacts:
          path: "/go/bin"